import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import AuthProvider from "./api/auth/sessionProvider";
import Navbar from "./components/Navbar";

import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" key="root-layout">
      <body className={inter.className}>
        <AuthProvider>
        {/* <Navbar /> */}
          {children}
          <ToastContainer />
        </AuthProvider>
    
      </body>
    </html>
  );
}
