const suggestionsList = [
    //UNITED STATES
    'New York, NY, United States',
'Los Angeles, CA, United States',
'Chicago, IL, United States',
'Houston, TX, United States',
'Phoenix, AZ, United States',
'Philadelphia, PA, United States',
'San Antonio, TX, United States',
'San Diego, CA, United States',
'Dallas, TX, United States',
'San Jose, CA, United States',
'Austin, TX, United States',
'Jacksonville, FL, United States',
'Fort Worth, TX, United States',
'Columbus, OH, United States',
'Charlotte, NC, United States',
'San Francisco, CA, United States',
'Indianapolis, IN, United States',
'Seattle, WA, United States',
'Denver, CO, United States',
'Washington, DC, United States',
'Boston, MA, United States',
'El Paso, TX, United States',
'Nashville, TN, United States',
'Detroit, MI, United States',
'Oklahoma City, OK, United States',
'Portland, OR, United States',
'Las Vegas, NV, United States',
'Memphis, TN, United States',
'Louisville, KY, United States',
'Baltimore, MD, United States',
'Milwaukee, WI, United States',
'Albuquerque, NM, United States',
'Tucson, AZ, United States',
'Fresno, CA, United States',
'Sacramento, CA, United States',
'Mesa, AZ, United States',
'Kansas City, MO, United States',
'Atlanta, GA, United States',
'Omaha, NE, United States',
'Colorado Springs, CO, United States',
'Raleigh, NC, United States',
'Miami, FL, United States',
'Virginia Beach, VA, United States',
'Oakland, CA, United States',
'Minneapolis, MN, United States',
'Tulsa, OK, United States',
'Arlington, TX, United States',
'Tampa, FL, United States',
'New Orleans, LA, United States',
'Wichita, KS, United States',
'Cleveland, OH, United States',
'Aurora, CO, United States',
'Anaheim, CA, United States',
'Honolulu, HI, United States',
'Santa Ana, CA, United States',
'Riverside, CA, United States',
'Corpus Christi, TX, United States',
'Lexington, KY, United States',
'Henderson, NV, United States',
'Stockton, CA, United States',
'Saint Paul, MN, United States',
'Cincinnati, OH, United States',
'St. Louis, MO, United States',
'Pittsburgh, PA, United States',
'Greensboro, NC, United States',
'Anchorage, AK, United States',
'Plano, TX, United States',
'Lincoln, NE, United States',
'Orlando, FL, United States',
'Irvine, CA, United States',
'Newark, NJ, United States',
'Toledo, OH, United States',
'Durham, NC, United States',
'Chula Vista, CA, United States',
'Fort Wayne, IN, United States',
'Jersey City, NJ, United States',
'St. Petersburg, FL, United States',
'Laredo, TX, United States',
'Madison, WI, United States',
'Chandler, AZ, United States',
'Buffalo, NY, United States',
'Lubbock, TX, United States',
'Scottsdale, AZ, United States',
'Reno, NV, United States',
'Glendale, AZ, United States',
'Gilbert, AZ, United States',
'Winston-Salem, NC, United States',
'North Las Vegas, NV, United States',
'Norfolk, VA, United States',
'Chesapeake, VA, United States',
'Garland, TX, United States',
'Irving, TX, United States',
'Hialeah, FL, United States',
'Fremont, CA, United States',
'Boise, ID, United States',
'Richmond, VA, United States',
'Baton Rouge, LA, United States',
'Spokane, WA, United States',
'Des Moines, IA, United States',
'Tacoma, WA, United States',
'San Bernardino, CA, United States',
'Modesto, CA, United States',
'Fontana, CA, United States',
'Santa Clarita, CA, United States',
'Birmingham, AL, United States',
'Oxnard, CA, United States',
'Fayetteville, NC, United States',
'Rochester, NY, United States',
'Moreno Valley, CA, United States',
'Glendale, CA, United States',
'Yonkers, NY, United States',
'Huntington Beach, CA, United States',
'Aurora, IL, United States',
'Columbus, GA, United States',
'Amarillo, TX, United States',
'Little Rock, AR, United States',
'Mobile, AL, United States',
'Chattanooga, TN, United States',
'Knoxville, TN, United States',
'Worcester, MA, United States',
'Grand Rapids, MI, United States',
'Salt Lake City, UT, United States',
'Tallahassee, FL, United States',
'Huntsville, AL, United States',
'Grand Prairie, TX, United States',
'Overland Park, KS, United States',
'Sioux Falls, SD, United States',
'Ontario, CA, United States',
'Vancouver, WA, United States',
'Tempe, AZ, United States',
'Springfield, MO, United States',
'Lancaster, CA, United States',
'Eugene, OR, United States',
'Pembroke Pines, FL, United States',
'Salem, OR, United States',
'Cape Coral, FL, United States',
'Peoria, AZ, United States',
'Sioux Falls, SD, United States',
'Santa Rosa, CA, United States',
'Joliet, IL, United States',
'Rockford, IL, United States',
'Paterson, NJ, United States',
'Naperville, IL, United States',
'Savannah, GA, United States',
'Bridgeport, CT, United States',
'Mesquite, TX, United States',
'Killeen, TX, United States',
'Syracuse, NY, United States',
'McAllen, TX, United States',
'Pasadena, TX, United States',
'Bellevue, WA, United States',
'Fullerton, CA, United States',
'Orange, CA, United States',
'Dayton, OH, United States',
'Miramar, FL, United States',
'Thornton, CO, United States',
'West Valley City, UT, United States',
'Olathe, KS, United States',
'Hampton, VA, United States',
'Warren, MI, United States',
'Midland, TX, United States',
'Charleston, SC, United States',
'Waco, TX, United States',
'Gainesville, FL, United States',
'Columbia, SC, United States',
'Carrollton, TX, United States',
'Visalia, CA, United States',
'Coral Springs, FL, United States',
'New Haven, CT, United States',
'Stamford, CT, United States',
'Concord, CA, United States',
'Kent, WA, United States',
'Lafayette, LA, United States',
'Topeka, KS, United States',
'Simi Valley, CA, United States',
'Santa Clara, CA, United States',
'Athens, GA, United States',
'Hartford, CT, United States',
'Victorville, CA, United States',
'Abilene, TX, United States',
'Norman, OK, United States',
'Vallejo, CA, United States',
'Berkeley, CA, United States',
'Round Rock, TX, United States',
'Ann Arbor, MI, United States',
'Fargo, ND, United States',
'Columbia, MO, United States',
'Allentown, PA, United States',
'Evansville, IN, United States',
'Beaumont, TX, United States',
'Odessa, TX, United States',
'Wilmington, NC, United States',
'Arvada, CO, United States',
'Independence, MO, United States',
'Provo, UT, United States',
'Lansing, MI, United States',
'El Monte, CA, United States',
'Springfield, MA, United States',
'Fairfield, CA, United States',
'Clearwater, FL, United States',
'Peoria, IL, United States',
'Rochester, MN, United States',
'Carlsbad, CA, United States',
'Westminster, CO, United States',
'West Jordan, UT, United States',
'Pearland, TX, United States',
'Richardson, TX, United States',
'Downey, CA, United States',
'Miami Gardens, FL, United States',
'Temecula, CA, United States',
'Costa Mesa, CA, United States',
'College Station, TX, United States',
'Elgin, IL, United States',
'Murfreesboro, TN, United States',
'Gresham, OR, United States',
'High Point, NC, United States',
'Antioch, CA, United States',
'Inglewood, CA, United States',
'Cambridge, MA, United States',
'Lowell, MA, United States',
'Manchester, NH, United States',
'Billings, MT, United States',
'Pueblo, CO, United States',
'Palm Bay, FL, United States',
'Centennial, CO, United States',
'Richmond, CA, United States',
'Ventura, CA, United States',
'Pompano Beach, FL, United States',
'North Charleston, SC, United States',
'Everett, WA, United States',
'Waterbury, CT, United States',
'West Palm Beach, FL, United States',
'Boulder, CO, United States',
'West Covina, CA, United States',
'Broken Arrow, OK, United States',
'Clovis, CA, United States',
'Daly City, CA, United States',
'Sandy Springs, GA, United States',
'Burbank, CA, United States',
'South Bend, IN, United States',
'Hesperia, CA, United States',
'Rialto, CA, United States',
'Lewisville, TX, United States',
'El Cajon, CA, United States',
'San Mateo, CA, United States',
'Redding, CA, United States',
'Fargo, ND, United States',
'Bend, OR, United States',
'Lakewood, CO, United States',
'Erie, PA, United States',
'Tyler, TX, United States',
'Pearland, TX, United States',
'Temecula, CA, United States',
'Springfield, IL, United States',
'Wilmington, DE, United States',
'Vallejo, CA, United States',
'Odessa, TX, United States',
'College Station, TX, United States',
'Green Bay, WI, United States',
'West Jordan, UT, United States',
'Antioch, CA, United States',
'Billings, MT, United States',
'Round Rock, TX, United States',
'Cambridge, MA, United States',
'Murrieta, CA, United States',
'Gresham, OR, United States',
'Lewisville, TX, United States',
'Palm Bay, FL, United States',
'Pompano Beach, FL, United States',
'West Palm Beach, FL, United States',
'Inglewood, CA, United States',
'Miami Gardens, FL, United States',
'Manchester, NH, United States',
'Downey, CA, United States',
'Clovis, CA, United States',
'Waterbury, CT, United States',
'South Bend, IN, United States',
'Erie, PA, United States',
'Daly City, CA, United States',
'Richardson, TX, United States',
'Las Cruces, NM, United States',
'Sandy Springs, GA, United States',
'Burbank, CA, United States',
'Green Bay, WI, United States',
'High Point, NC, United States',
'Westminster, CO, United States',
'Burbank, CA, United States',
'Palm Coast, FL, United States',
'Fairfield, CA, United States',
'San Mateo, CA, United States',
'El Monte, CA, United States',
'North Charleston, SC, United States',
'Temecula, CA, United States',
'Gresham, OR, United States',
'Concord, CA, United States',
'Tyler, TX, United States',
'Rialto, CA, United States',
'Odessa, TX, United States',
'Broken Arrow, OK, United States',
'High Point, NC, United States',
'Billings, MT, United States',
'Berkeley, CA, United States',
'Lowell, MA, United States',
'Wilmington, DE, United States',
'San Mateo, CA, United States',
'Las Cruces, NM, United States',
'Longmont, CO, United States',
'Bend, OR, United States',
'Palm Bay, FL, United States',
'Redding, CA, United States',
'West Jordan, UT, United States',
'Tyler, TX, United States',
'Vallejo, CA, United States',
'Lewisville, TX, United States',
'El Cajon, CA, United States',
'Round Rock, TX, United States',
'North Charleston, SC, United States',
'Miami Gardens, FL, United States',
'College Station, TX, United States',
'Pompano Beach, FL, United States',
'Broken Arrow, OK, United States',
'Bend, OR, United States',

    //UNITED KINGDOM
    'London, England, United Kingdom',
'Birmingham, West Midlands, United Kingdom',
'Manchester, Greater Manchester, United Kingdom',
'Liverpool, Merseyside, United Kingdom',
'Leeds, West Yorkshire, United Kingdom',
'Sheffield, South Yorkshire, United Kingdom',
'Bristol, England, United Kingdom',
'Glasgow, Scotland, United Kingdom',
'Edinburgh, Scotland, United Kingdom',
'Leicester, Leicestershire, United Kingdom',
'Coventry, West Midlands, United Kingdom',
'Kingston upon Hull, East Riding of Yorkshire, United Kingdom',
'Cardiff, Wales, United Kingdom',
'Bradford, West Yorkshire, United Kingdom',
'Belfast, Northern Ireland, United Kingdom',
'Stoke-on-Trent, Staffordshire, United Kingdom',
'Wolverhampton, West Midlands, United Kingdom',
'Nottingham, Nottinghamshire, United Kingdom',
'Plymouth, Devon, United Kingdom',
'Southampton, Hampshire, United Kingdom',
'Reading, Berkshire, United Kingdom',
'Derby, Derbyshire, United Kingdom',
'Dudley, West Midlands, United Kingdom',
'Newcastle upon Tyne, Tyne and Wear, United Kingdom',
'Northampton, Northamptonshire, United Kingdom',
'Portsmouth, Hampshire, United Kingdom',
'Luton, Bedfordshire, United Kingdom',
'Preston, Lancashire, United Kingdom',
'Aberdeen, Scotland, United Kingdom',
'Milton Keynes, Buckinghamshire, United Kingdom',
'Sunderland, Tyne and Wear, United Kingdom',
'Norwich, Norfolk, United Kingdom',
'Woking, Surrey, United Kingdom',
'Swansea, Wales, United Kingdom',
'Oxford, Oxfordshire, United Kingdom',
'Cambridge, Cambridgeshire, United Kingdom',
'Slough, Berkshire, United Kingdom',
'York, North Yorkshire, United Kingdom',
'Blackpool, Lancashire, United Kingdom',
'Bolton, Greater Manchester, United Kingdom',
'Ipswich, Suffolk, United Kingdom',
'Peterborough, Cambridgeshire, United Kingdom',
'Stockport, Greater Manchester, United Kingdom',
'Rotherham, South Yorkshire, United Kingdom',
'Brighton, East Sussex, United Kingdom',
'Hove, East Sussex, United Kingdom',
'Telford, Shropshire, United Kingdom',
'Gloucester, Gloucestershire, United Kingdom',
'Exeter, Devon, United Kingdom',
'Watford, Hertfordshire, United Kingdom',
'Colchester, Essex, United Kingdom',
'Basildon, Essex, United Kingdom',
'Cheltenham, Gloucestershire, United Kingdom',
'Chelmsford, Essex, United Kingdom',
'Basingstoke, Hampshire, United Kingdom',
'Lincoln, Lincolnshire, United Kingdom',
'Oldham, Greater Manchester, United Kingdom',
'Warrington, Cheshire, United Kingdom',
'Gateshead, Tyne and Wear, United Kingdom',
'Lisburn, Northern Ireland, United Kingdom',
'Bath, Somerset, United Kingdom',
'Solihull, West Midlands, United Kingdom',
'Bournemouth, Dorset, United Kingdom',
'Poole, Dorset, United Kingdom',
'Chesterfield, Derbyshire, United Kingdom',
'Worcester, Worcestershire, United Kingdom',
'Newport, Wales, United Kingdom',
'High Wycombe, Buckinghamshire, United Kingdom',
'Wokingham, Berkshire, United Kingdom',
'Dundee, Scotland, United Kingdom',
'St Albans, Hertfordshire, United Kingdom',
'Rochdale, Greater Manchester, United Kingdom',
'Barnsley, South Yorkshire, United Kingdom',
'Swindon, Wiltshire, United Kingdom',
'Darlington, County Durham, United Kingdom',
'Maidstone, Kent, United Kingdom',
'Doncaster, South Yorkshire, United Kingdom',
'Paisley, Scotland, United Kingdom',
'Bracknell, Berkshire, United Kingdom',
'Tonbridge, Kent, United Kingdom',
'Blackburn, Lancashire, United Kingdom',
'Hastings, East Sussex, United Kingdom',
'Burnley, Lancashire, United Kingdom',
'Rugby, Warwickshire, United Kingdom',
'Scarborough, North Yorkshire, United Kingdom',
'Grimsby, Lincolnshire, United Kingdom',
'Salford, Greater Manchester, United Kingdom',
'Greenwich, London, United Kingdom',
'Shrewsbury, Shropshire, United Kingdom',
'Crewe, Cheshire, United Kingdom',
'Newbury, Berkshire, United Kingdom',
'Walsall, West Midlands, United Kingdom',
'Bury, Greater Manchester, United Kingdom',
'Harlow, Essex, United Kingdom',
'Farnborough, Hampshire, United Kingdom',
'Whitehaven, Cumbria, United Kingdom',
'Aldershot, Hampshire, United Kingdom',
'Dover, Kent, United Kingdom',
'Stevenage, Hertfordshire, United Kingdom',
'Northwich, Cheshire, United Kingdom',
'Stafford, Staffordshire, United Kingdom',
'Bexley, London, United Kingdom',
'Ruislip, London, United Kingdom',
'Yeovil, Somerset, United Kingdom',
'Margate, Kent, United Kingdom',
'Welwyn Garden City, Hertfordshire, United Kingdom',
'Redditch, Worcestershire, United Kingdom',
'Lowestoft, Suffolk, United Kingdom',
'Bromley, London, United Kingdom',
'Beckenham, London, United Kingdom',
'Sutton, London, United Kingdom',
'Barnet, London, United Kingdom',
'Enfield, London, United Kingdom',
'Stoke Newington, London, United Kingdom',
'Bethnal Green, London, United Kingdom',
'Clapham, London, United Kingdom',
'East Ham, London, United Kingdom',
'Wimbledon, London, United Kingdom',
'Tooting, London, United Kingdom',
'Muswell Hill, London, United Kingdom',
'Maida Vale, London, United Kingdom',
'Kensington, London, United Kingdom',
'Mayfair, London, United Kingdom',
'Fulham, London, United Kingdom',
'Brentwood, Essex, United Kingdom',
'Hayes, Middlesex, United Kingdom',
'Ilford, Essex, United Kingdom',
'Croydon, London, United Kingdom',
'Leytonstone, London, United Kingdom',
'Stratford, London, United Kingdom',
'Leyton, London, United Kingdom',
'Isleworth, Middlesex, United Kingdom',
'Feltham, Middlesex, United Kingdom',
'Hounslow, Middlesex, United Kingdom',
'Streatham, London, United Kingdom',
'Dulwich, London, United Kingdom',
'Finchley, London, United Kingdom',
'Hendon, London, United Kingdom',
'Edgware, London, United Kingdom',
'Harrow, Middlesex, United Kingdom',
'Wembley, Middlesex, United Kingdom',
'Hillingdon, Middlesex, United Kingdom',
'Acton, London, United Kingdom',
'Ealing, London, United Kingdom',
'Chiswick, London, United Kingdom',
'Paddington, London, United Kingdom',
'Hammersmith, London, United Kingdom',
'Bayswater, London, United Kingdom',
'Bloomsbury, London, United Kingdom',
'Holborn, London, United Kingdom',
'Bishopsgate, London, United Kingdom',
'Shoreditch, London, United Kingdom',
'Whitechapel, London, United Kingdom',
'Lambeth, London, United Kingdom',
'Camberwell, London, United Kingdom',
'Greenwich, London, United Kingdom',
'Deptford, London, United Kingdom',
'Peckham, London, United Kingdom',
'Battersea, London, United Kingdom',
'Brixton, London, United Kingdom',
'Wandsworth, London, United Kingdom',
'Putney, London, United Kingdom',
'Roehampton, London, United Kingdom',
'Camden Town, London, United Kingdom',
'Hampstead, London, United Kingdom',
'Kilburn, London, United Kingdom',
'Notting Hill, London, United Kingdom',
'Kensington, London, United Kingdom',
'Chelsea, London, United Kingdom',
'Westminster, London, United Kingdom',
'Marylebone, London, United Kingdom',
'Belgravia, London, United Kingdom',
'Clerkenwell, London, United Kingdom',
'Finsbury, London, United Kingdom',
'Stoke Newington, London, United Kingdom',
'Dalston, London, United Kingdom',
'Hoxton, London, United Kingdom',
'Haggerston, London, United Kingdom',
'Islington, London, United Kingdom',
'Canonbury, London, United Kingdom',
'Finsbury Park, London, United Kingdom',
'Highbury, London, United Kingdom',
'Holloway, London, United Kingdom',
'Archway, London, United Kingdom',
'Tufnell Park, London, United Kingdom',
'Barnsbury, London, United Kingdom',
'Kentish Town, London, United Kingdom',
'Chalk Farm, London, United Kingdom',
'Belsize Park, London, United Kingdom',
'South Hampstead, London, United Kingdom',
'Swiss Cottage, London, United Kingdom',
'Fitzrovia, London, United Kingdom',
'Soho, London, United Kingdom',
'Covent Garden, London, United Kingdom',
'Mayfair, London, United Kingdom',
'Victoria, London, United Kingdom',
'Pimlico, London, United Kingdom',
'Nine Elms, London, United Kingdom',
'Battersea, London, United Kingdom',
'Clapham, London, United Kingdom',
'Balham, London, United Kingdom',
'Wandsworth, London, United Kingdom',
'Tooting, London, United Kingdom',
'Furzedown, London, United Kingdom',
'Colliers Wood, London, United Kingdom',
'Southfields, London, United Kingdom',
'Wimbledon, London, United Kingdom',
'Raynes Park, London, United Kingdom',
'Morden, London, United Kingdom',
'Mitcham, London, United Kingdom',
'Carshalton, London, United Kingdom',
'Wallington, London, United Kingdom',
'Coulsdon, London, United Kingdom',
'Purley, London, United Kingdom',
'Sanderstead, London, United Kingdom',
'Croydon, London, United Kingdom',
'Thornton Heath, London, United Kingdom',
'Norbury, London, United Kingdom',
'Streatham, London, United Kingdom',
'West Norwood, London, United Kingdom',
'Crystal Palace, London, United Kingdom',
'Dulwich, London, United Kingdom',
'Forest Hill, London, United Kingdom',
'Sydenham, London, United Kingdom',
'Catford, London, United Kingdom',
'Lewisham, London, United Kingdom',
'Brockley, London, United Kingdom',
'New Cross, London, United Kingdom',
'Deptford, London, United Kingdom',
'Greenwich, London, United Kingdom',
'Charlton, London, United Kingdom',
'Eltham, London, United Kingdom',
'Kidbrooke, London, United Kingdom',
'Blackheath, London, United Kingdom',
'Lee, London, United Kingdom',
'Grove Park, London, United Kingdom',
'Downham, London, United Kingdom',
'Bellingham, London, United Kingdom',
'Sydenham, London, United Kingdom',
'Forest Hill, London, United Kingdom',
'Honor Oak, London, United Kingdom',
'Brockley, London, United Kingdom',
'New Cross, London, United Kingdom',
'Deptford, London, United Kingdom',
'Greenwich, London, United Kingdom',
'Blackheath, London, United Kingdom',
'Charlton, London, United Kingdom',
'Plumstead, London, United Kingdom',
'Eltham, London, United Kingdom',
'Mottingham, London, United Kingdom',
'Grove Park, London, United Kingdom',
'Lee, London, United Kingdom',
'Lewisham, London, United Kingdom',
'Catford, London, United Kingdom',
'Bellingham, London, United Kingdom',
'Downham, London, United Kingdom',
'Beckenham, London, United Kingdom',
'Penge, London, United Kingdom',
'Bromley, London, United Kingdom',
'Orpington, London, United Kingdom',
'Chislehurst, London, United Kingdom',
'Hayes, London, United Kingdom',
'West Wickham, London, United Kingdom',
'Biggin Hill, London, United Kingdom',
'Sidcup, London, United Kingdom',
'Bexley, London, United Kingdom',
'Welling, London, United Kingdom',
'Bexleyheath, London, United Kingdom',
'Crayford, London, United Kingdom',
'Erith, London, United Kingdom',
'Thamesmead, London, United Kingdom',
'Abbey Wood, London, United Kingdom',
'Belvedere, London, United Kingdom',
'Upper Edmonton, London, United Kingdom',
'Lower Edmonton, London, United Kingdom',
'Enfield, London, United Kingdom',
'Ponders End, London, United Kingdom',
'Edmonton, London, United Kingdom',
'Palmers Green, London, United Kingdom',
'Winchmore Hill, London, United Kingdom',
'Southgate, London, United Kingdom',
'Arnos Grove, London, United Kingdom',
'Bounds Green, London, United Kingdom',
'Wood Green, London, United Kingdom',
'Harringay, London, United Kingdom',
'Manor House, London, United Kingdom',
'Seven Sisters, London, United Kingdom',
'Tottenham, London, United Kingdom',
'Stamford Hill, London, United Kingdom',
'Hackney, London, United Kingdom',
'Dalston, London, United Kingdom',
'Shoreditch, London, United Kingdom',
'Bethnal Green, London, United Kingdom',
'Whitechapel, London, United Kingdom',
'Aldgate, London, United Kingdom',
'Stepney, London, United Kingdom',
'Mile End, London, United Kingdom',
'Bow, London, United Kingdom',
'Poplar, London, United Kingdom',
'Canary Wharf, London, United Kingdom',
'Blackwall, London, United Kingdom',
'Isle of Dogs, London, United Kingdom',
'Cubitt Town, London, United Kingdom',
'Limehouse, London, United Kingdom',
'Wapping, London, United Kingdom',
'St Katharine Docks, London, United Kingdom',
'Shadwell, London, United Kingdom',
'Ratcliff, London, United Kingdom',
'Whitechapel, London, United Kingdom',
'Spitalfields, London, United Kingdom',
'Brick Lane, London, United Kingdom',
'Aldgate, London, United Kingdom',
'Tower Hill, London, United Kingdom',
'London Bridge, London, United Kingdom',
'Southwark, London, United Kingdom',
'Bermondsey, London, United Kingdom',
'Rotherhithe, London, United Kingdom',
'Surrey Quays, London, United Kingdom',
'Canada Water, London, United Kingdom',
'Deptford, London, United Kingdom',
'Greenwich, London, United Kingdom',
'Blackheath, London, United Kingdom',
'Kidbrooke, London, United Kingdom',
'Eltham, London, United Kingdom',
'Woolwich, London, United Kingdom',
'Plumstead, London, United Kingdom',
'Thamesmead, London, United Kingdom',
'Charlton, London, United Kingdom',
'Silvertown, London, United Kingdom',
'North Woolwich, London, United Kingdom',
'West Ham, London, United Kingdom',
'Canning Town, London, United Kingdom',
'Stratford, London, United Kingdom',
'Leyton, London, United Kingdom',
'Leytonstone, London, United Kingdom',
'Walthamstow, London, United Kingdom',
'Chingford, London, United Kingdom',
'Highams Park, London, United Kingdom',
'Woodford, London, United Kingdom',
'Snaresbrook, London, United Kingdom',
'South Woodford, London, United Kingdom',
'Wanstead, London, United Kingdom',
'Redbridge, London, United Kingdom',
'Ilford, London, United Kingdom',
'Barkingside, London, United Kingdom',
'Seven Kings, London, United Kingdom',
'Goodmayes, London, United Kingdom',
'Chadwell Heath, London, United Kingdom',
'Dagenham, London, United Kingdom',
'Rush Green, London, United Kingdom',
'Romford, London, United Kingdom',
'Harold Hill, London, United Kingdom',
'Collier Row, London, United Kingdom',
'Upminster, London, United Kingdom',
'Rainham, London, United Kingdom',
'Hornchurch, London, United Kingdom',
'Cranham, London, United Kingdom',
'Purfleet, London, United Kingdom',
'Aveley, London, United Kingdom',
'Thurrock, London, United Kingdom',
'Grays, London, United Kingdom',
'Tilbury, London, United Kingdom',
'North Stifford, London, United Kingdom',
'South Ockendon, London, United Kingdom',
'West Thurrock, London, United Kingdom',
'Erith, London, United Kingdom',
'Crayford, London, United Kingdom',
'Dartford, London, United Kingdom',
'Bexleyheath, London, United Kingdom',
'Welling, London, United Kingdom',
'Belvedere, London, United Kingdom',
'Abbey Wood, London, United Kingdom',
'Charlton, London, United Kingdom',
'Kidbrooke, London, United Kingdom',
'Blackheath, London, United Kingdom',
'Deptford, London, United Kingdom',
'Greenwich, London, United Kingdom',
'New Cross, London, United Kingdom',
'Brockley, London, United Kingdom',
'Honor Oak, London, United Kingdom',
'Forest Hill, London, United Kingdom',

// SPAIN

'Madrid, Community of Madrid, Spain',
'Barcelona, Catalonia, Spain',
'Valencia, Valencian Community, Spain',
'Seville, Andalusia, Spain',
'Zaragoza, Aragon, Spain',
'Málaga, Andalusia, Spain',
'Murcia, Region of Murcia, Spain',
'Palma, Balearic Islands, Spain',
'Las Palmas de Gran Canaria, Canary Islands, Spain',
'Bilbao, Basque Country, Spain',
'Alicante, Valencian Community, Spain',
'Córdoba, Andalusia, Spain',
'Valladolid, Castile and León, Spain',
'Vigo, Galicia, Spain',
'Gijón, Asturias, Spain',
'Hospitalet de Llobregat, Catalonia, Spain',
'A Coruña, Galicia, Spain',
'Vitoria-Gasteiz, Basque Country, Spain',
'Granada, Andalusia, Spain',
'Elche, Valencian Community, Spain',
'Oviedo, Asturias, Spain',
'Santa Cruz de Tenerife, Canary Islands, Spain',
'Badalona, Catalonia, Spain',
'Cartagena, Region of Murcia, Spain',
'Terrassa, Catalonia, Spain',
'Jerez de la Frontera, Andalusia, Spain',
'Sabadell, Catalonia, Spain',
'Móstoles, Community of Madrid, Spain',
'Alcalá de Henares, Community of Madrid, Spain',
'Pamplona, Navarre, Spain',
'Fuenlabrada, Community of Madrid, Spain',
'Almería, Andalusia, Spain',
'San Sebastián, Basque Country, Spain',
'Leganés, Community of Madrid, Spain',
'Getafe, Community of Madrid, Spain',
'Burgos, Castile and León, Spain',
'Albacete, Castile-La Mancha, Spain',
'Santander, Cantabria, Spain',
'Castellón de la Plana, Valencian Community, Spain',
'Alcorcón, Community of Madrid, Spain',
'Sant Boi de Llobregat, Catalonia, Spain',
'Logroño, La Rioja, Spain',
'Badajoz, Extremadura, Spain',
'Salamanca, Castile and León, Spain',
'Huelva, Andalusia, Spain',
'Marbella, Andalusia, Spain',
'Lleida, Catalonia, Spain',
'Tarragona, Catalonia, Spain',
'Cádiz, Andalusia, Spain',
'Lugo, Galicia, Spain',
'Algeciras, Andalusia, Spain',
'Ourense, Galicia, Spain',
'León, Castile and León, Spain',
'Girona, Catalonia, Spain',
'Cáceres, Extremadura, Spain',
'Lorca, Region of Murcia, Spain',
'Alcobendas, Community of Madrid, Spain',
'Jaén, Andalusia, Spain',
'Pontevedra, Galicia, Spain',
'Parla, Community of Madrid, Spain',
'San Fernando, Andalusia, Spain',
'Torrevieja, Valencian Community, Spain',
'Coslada, Community of Madrid, Spain',
'Guadalajara, Castile-La Mancha, Spain',
'Ciudad Real, Castile-La Mancha, Spain',
'Rubí, Catalonia, Spain',
'Majadahonda, Community of Madrid, Spain',
'Fuenlabrada, Community of Madrid, Spain',
'San Sebastián de los Reyes, Community of Madrid, Spain',
'Ferrol, Galicia, Spain',
'Las Rozas, Community of Madrid, Spain',
'Palencia, Castile and León, Spain',
'Zamora, Castile and León, Spain',
'La Laguna, Canary Islands, Spain',
'Huesca, Aragon, Spain',
'Paterna, Valencian Community, Spain',
'Elda, Valencian Community, Spain',
'Segovia, Castile and León, Spain',
'Pozuelo de Alarcón, Community of Madrid, Spain',
'La Línea de la Concepción, Andalusia, Spain',
'Almería, Andalusia, Spain',
'Torremolinos, Andalusia, Spain',
'El Puerto de Santa María, Andalusia, Spain',
'Manresa, Catalonia, Spain',
'Viladecans, Catalonia, Spain',
'Vélez-Málaga, Andalusia, Spain',
'Roquetas de Mar, Andalusia, Spain',
'Benidorm, Valencian Community, Spain',
'Getxo, Basque Country, Spain',
'Alzira, Valencian Community, Spain',
'Rivas-Vaciamadrid, Community of Madrid, Spain',
'Ávila, Castile and León, Spain',
'Cuenca, Castile-La Mancha, Spain',
'Paterna, Valencian Community, Spain',
'Alcoy, Valencian Community, Spain',
'Vilanova i la Geltrú, Catalonia, Spain',
'Talavera de la Reina, Castile-La Mancha, Spain',
'Irun, Basque Country, Spain',
'Zarautz, Basque Country, Spain',
'Villanueva de la Serena, Extremadura, Spain',
'Puertollano, Castile-La Mancha, Spain',
'Inca, Balearic Islands, Spain',
'Rincón de la Victoria, Andalusia, Spain',
'Benalmádena, Andalusia, Spain',
'Molina de Segura, Region of Murcia, Spain',
'Santiago de Compostela, Galicia, Spain',
'Toledo, Castile-La Mancha, Spain',
'Ponferrada, Castile and León, Spain',
'Torrelavega, Cantabria, Spain',
'Ronda, Andalusia, Spain',
'Alhaurín de la Torre, Andalusia, Spain',
'Sanlúcar de Barrameda, Andalusia, Spain',
'Antequera, Andalusia, Spain',
'Mérida, Extremadura, Spain',
'Ceuta, Ceuta, Spain',
'Melilla, Melilla, Spain',
'Motril, Andalusia, Spain',
'Aranjuez, Community of Madrid, Spain',
'Arrecife, Canary Islands, Spain',
'Barbate, Andalusia, Spain',
'Tudela, Navarre, Spain',
'Ibiza Town, Balearic Islands, Spain',
`Port d'Andratx, Balearic Islands, Spain`,
'Sant Antoni de Portmany, Balearic Islands, Spain',
'Santa Eulària des Riu, Balearic Islands, Spain',
'Sant Josep de sa Talaia, Balearic Islands, Spain',
'Formentera, Balearic Islands, Spain',
'Calvià, Balearic Islands, Spain',
'Magaluf, Balearic Islands, Spain',
'Palmanova, Balearic Islands, Spain',
'Peguera, Balearic Islands, Spain',
'Santa Ponça, Balearic Islands, Spain',
'Sant Llorenç des Cardassar, Balearic Islands, Spain',
'Sineu, Balearic Islands, Spain',
'Santanyí, Balearic Islands, Spain',
'Son Servera, Balearic Islands, Spain',
'Campos, Balearic Islands, Spain',
'Felanitx, Balearic Islands, Spain',
'Portocolom, Balearic Islands, Spain',
'Capdepera, Balearic Islands, Spain',
'Cala Ratjada, Balearic Islands, Spain',
'Manacor, Balearic Islands, Spain',
'Artà, Balearic Islands, Spain',
'Muro, Balearic Islands, Spain',
'Alcúdia, Balearic Islands, Spain',
'Pollença, Balearic Islands, Spain',
'Valldemossa, Balearic Islands, Spain',
'Deyá, Balearic Islands, Spain',
'Andratx, Balearic Islands, Spain',
'Bunyola, Balearic Islands, Spain',
'Esporles, Balearic Islands, Spain',
'Santa Maria del Camí, Balearic Islands, Spain',
'Marratxí, Balearic Islands, Spain',
'Algaida, Balearic Islands, Spain',
'Lloret de Vistalegre, Balearic Islands, Spain',
'Llubi, Balearic Islands, Spain',
'Sencelles, Balearic Islands, Spain',
'Selva, Balearic Islands, Spain',
'Lloseta, Balearic Islands, Spain',
'Alaró, Balearic Islands, Spain',
'Binissalem, Balearic Islands, Spain',
'Consell, Balearic Islands, Spain',
'Montuïri, Balearic Islands, Spain',
'Petra, Balearic Islands, Spain',
'Porreres, Balearic Islands, Spain',
'Vilafranca de Bonany, Balearic Islands, Spain',
'Sant Joan, Balearic Islands, Spain',
'Maria de la Salut, Balearic Islands, Spain',
'Santa Margalida, Balearic Islands, Spain',
'Lloret de Mar, Catalonia, Spain',
'Blanes, Catalonia, Spain',
'Malgrat de Mar, Catalonia, Spain',
'Calella, Catalonia, Spain',
'Santa Susanna, Catalonia, Spain',
'Pineda de Mar, Catalonia, Spain',
'Canet de Mar, Catalonia, Spain',
'Sant Pol de Mar, Catalonia, Spain',
'Arenys de Mar, Catalonia, Spain',
'Mataró, Catalonia, Spain',
'Sant Andreu de Llavaneres, Catalonia, Spain',
'Sant Vicenç de Montalt, Catalonia, Spain',
`Caldes d'Estrac, Catalonia, Spain`,
'Arenys de Munt, Catalonia, Spain',
'Sant Iscle de Vallalta, Catalonia, Spain',
'Sant Cebrià de Vallalta, Catalonia, Spain',
'Canet de Mar, Catalonia, Spain',
'Palafolls, Catalonia, Spain',
'Sant Genís de Palafolls, Catalonia, Spain',
'Malgrat de Mar, Catalonia, Spain',
'Sant Pere de Vilamajor, Catalonia, Spain',
'Fogars de la Selva, Catalonia, Spain',
'Riells i Viabrea, Catalonia, Spain',
'Hostalric, Catalonia, Spain',
'Arbúcies, Catalonia, Spain',
'Sant Hilari Sacalm, Catalonia, Spain',
'Breda, Catalonia, Spain',
'Viladrau, Catalonia, Spain',
'Montseny, Catalonia, Spain',
'Seva, Catalonia, Spain',
'El Brull, Catalonia, Spain',
'Aiguafreda, Catalonia, Spain',
'Sant Martí de Centelles, Catalonia, Spain',
'Tagamanent, Catalonia, Spain',
'La Garriga, Catalonia, Spain',
`L'Ametlla del Vallès, Catalonia, Spain`,
'Les Franqueses del Vallès, Catalonia, Spain',
'Granollers, Catalonia, Spain',
'Canovelles, Catalonia, Spain',
'Montmeló, Catalonia, Spain',
'Montornès del Vallès, Catalonia, Spain',
'Vilanova del Vallès, Catalonia, Spain',
'Vallromanes, Catalonia, Spain',
'Alella, Catalonia, Spain',
'Teià, Catalonia, Spain',
'El Masnou, Catalonia, Spain',
'Premià de Dalt, Catalonia, Spain',
'Premià de Mar, Catalonia, Spain',
'Vilassar de Dalt, Catalonia, Spain',
'Vilassar de Mar, Catalonia, Spain',
'Cabrianes, Catalonia, Spain',
'Calaf, Catalonia, Spain',
'Calders, Catalonia, Spain',
'Cardona, Catalonia, Spain',
'Castellbell i el Vilar, Catalonia, Spain',
'Castellfollit del Boix, Catalonia, Spain',
'Castellgalí, Catalonia, Spain',
'Castellnou de Bages, Catalonia, Spain',
'Castellolí, Catalonia, Spain',
'Collbató, Catalonia, Spain',
'El Bruc, Catalonia, Spain',
'Esparreguera, Catalonia, Spain',
'Manresa, Catalonia, Spain',
'Marganell, Catalonia, Spain',
'Monistrol de Montserrat, Catalonia, Spain',
'Mura, Catalonia, Spain',
'Navarcles, Catalonia, Spain',
'Navàs, Catalonia, Spain',
'Òdena, Catalonia, Spain',
'Oló, Catalonia, Spain',
'Oristà, Catalonia, Spain',
'Perafita, Catalonia, Spain',
'Piera, Catalonia, Spain',
'Pontons, Catalonia, Spain',
'Prats de Lluçanès, Catalonia, Spain',
'Puig-reig, Catalonia, Spain',
'Rajadell, Catalonia, Spain',
'Rellinars, Catalonia, Spain',
'Rubió, Catalonia, Spain',
'Sallent, Catalonia, Spain',
'Santa Cecília de Voltregà, Catalonia, Spain',
'Santa Eugènia de Berga, Catalonia, Spain',
'Santa Eulàlia de Riuprimer, Catalonia, Spain',
`Santa Maria d'Oló, Catalonia, Spain`,
'Sant Bartomeu del Grau, Catalonia, Spain',
'Sant Esteve de Palautordera, Catalonia, Spain',
'Sant Feliu Sasserra, Catalonia, Spain',
'Sant Fost de Campsentelles, Catalonia, Spain',
'Sant Hipòlit de Voltregà, Catalonia, Spain',
'Sant Jaume de Frontanyà, Catalonia, Spain',
'Sant Julià de Vilatorta, Catalonia, Spain',
'Sant Martí de Tous, Catalonia, Spain',
'Sant Mateu de Bages, Catalonia, Spain',
'Sant Pere Sallavinera, Catalonia, Spain',
'Sant Quirze Safaja, Catalonia, Spain',
`Sant Sadurní d'Anoia, Catalonia, Spain`,
'Sant Vicenç de Castellet, Catalonia, Spain',
'Súria, Catalonia, Spain',
'Talamanca, Catalonia, Spain',
'Taradell, Catalonia, Spain',
'Tavertet, Catalonia, Spain',
'Tona, Catalonia, Spain',
'Torelló, Catalonia, Spain',
'Vacarisses, Catalonia, Spain',
`Vallbona d'Anoia, Catalonia, Spain`,
'Veciana, Catalonia, Spain',
'Vic, Catalonia, Spain',
'Viladecavalls, Catalonia, Spain',
'Vilanova de Sau, Catalonia, Spain',
'Viver i Serrateix, Catalonia, Spain',
'Avinyó, Catalonia, Spain',
'Balsareny, Catalonia, Spain',
'Calaf, Catalonia, Spain',
'Callús, Catalonia, Spain',
'Capellades, Catalonia, Spain',
'Cardona, Catalonia, Spain',
'Castellbell i el Vilar, Catalonia, Spain',
'Castellcir, Catalonia, Spain',
'Castelldefels, Catalonia, Spain',
'Castellfollit del Boix, Catalonia, Spain',
'Castellgalí, Catalonia, Spain',
'Castellnou de Bages, Catalonia, Spain',
'Collbató, Catalonia, Spain',
'El Bruc, Catalonia, Spain',
'Esparreguera, Catalonia, Spain',
'Gelida, Catalonia, Spain',
'Granera, Catalonia, Spain',
'Hostalets de Pierola, Catalonia, Spain',
'Igualada, Catalonia, Spain',
'Jorba, Catalonia, Spain',
'Marganell, Catalonia, Spain',
'Martorell, Catalonia, Spain',
'Masquefa, Catalonia, Spain',
'Mediona, Catalonia, Spain',
'Moià, Catalonia, Spain',
'Monistrol de Montserrat, Catalonia, Spain',
'Mura, Catalonia, Spain',
'Navarcles, Catalonia, Spain',
'Navàs, Catalonia, Spain',
'Òdena, Catalonia, Spain',
'Oló, Catalonia, Spain',
'Orpí, Catalonia, Spain',
'Piera, Catalonia, Spain',
'Pontons, Catalonia, Spain',
'Rajadell, Catalonia, Spain',
'Rellinars, Catalonia, Spain',
'Rubió, Catalonia, Spain',
'Sant Esteve Sesrovires, Catalonia, Spain',
'Sant Feliu de Codines, Catalonia, Spain',
'Sant Hipòlit de Voltregà, Catalonia, Spain',
'Sant Jaume de Frontanyà, Catalonia, Spain',
'Sant Julià de Vilatorta, Catalonia, Spain',
'Sant Martí de Tous, Catalonia, Spain',
'Sant Mateu de Bages, Catalonia, Spain',
'Sant Pere Sallavinera, Catalonia, Spain',
'Sant Quirze Safaja, Catalonia, Spain',
`Sant Sadurní d'Anoia, Catalonia, Spain`,
'Sant Vicenç de Castellet, Catalonia, Spain',
'Súria, Catalonia, Spain',
'Talamanca, Catalonia, Spain',
'Taradell, Catalonia, Spain',
'Tavertet, Catalonia, Spain',
'Tona, Catalonia, Spain',
'Torelló, Catalonia, Spain',
'Vacarisses, Catalonia, Spain',
`Vallbona d'Anoia, Catalonia, Spain`,
'Veciana, Catalonia, Spain',
'Vic, Catalonia, Spain',
'Viladecavalls, Catalonia, Spain',
'Vilanova de Sau, Catalonia, Spain',
'Viver i Serrateix, Catalonia, Spain',
'Sant Boi de Llobregat, Catalonia, Spain',
'Sant Celoni, Catalonia, Spain',
'Sant Climent de Llobregat, Catalonia, Spain',
'Sant Cugat del Vallès, Catalonia, Spain',
'Sant Feliu de Llobregat, Catalonia, Spain',
'Sant Joan Despí, Catalonia, Spain',
'Sant Just Desvern, Catalonia, Spain',
`Sant Llorenç d'Hortons, Catalonia, Spain`,
'Sant Pere de Ribes, Catalonia, Spain',
'Sant Pol de Mar, Catalonia, Spain',
'Sant Quirze del Vallès, Catalonia, Spain',
`Sant Sadurní d'Anoia, Catalonia, Spain`,
'Sant Vicenç dels Horts, Catalonia, Spain',
'Santa Coloma de Cervelló, Catalonia, Spain',
'Sitges, Catalonia, Spain',
'Súria, Catalonia, Spain',
'Teià, Catalonia, Spain',
'Tona, Catalonia, Spain',
'Tordera, Catalonia, Spain',
'Torelló, Catalonia, Spain',
'Torrelavit, Catalonia, Spain',
'Torrelles de Foix, Catalonia, Spain',
'Torrelles de Llobregat, Catalonia, Spain',
'Vacarisses, Catalonia, Spain',
`Vallbona d'Anoia, Catalonia, Spain`,
'Vallgorguina, Catalonia, Spain',
'Vallirana, Catalonia, Spain',
'Vallromanes, Catalonia, Spain',
'Viladecans, Catalonia, Spain',
'Vilalba Sasserra, Catalonia, Spain',
'Vilassar de Dalt, Catalonia, Spain',
'Vilassar de Mar, Catalonia, Spain',
'Vilanova del Vallès, Catalonia, Spain',
'Vilanova i la Geltrú, Catalonia, Spain',
'Viver i Serrateix, Catalonia, Spain',


// GREECE

'Athens, Attica, Greece',
'Thessaloniki, Central Macedonia, Greece',
'Patras, Western Greece, Greece',
'Heraklion, Crete, Greece',
'Larissa, Thessaly, Greece',
'Volos, Thessaly, Greece',
'Rhodes, South Aegean, Greece',
'Ioannina, Epirus, Greece',
'Chania, Crete, Greece',
'Chalcis, Central Greece, Greece',
'Kalamata, Peloponnese, Greece',
'Serres, Central Macedonia, Greece',
'Alexandroupoli, Eastern Macedonia and Thrace, Greece',
'Xanthi, Eastern Macedonia and Thrace, Greece',
'Kavala, Eastern Macedonia and Thrace, Greece',
'Drama, Eastern Macedonia and Thrace, Greece',
'Komotini, Eastern Macedonia and Thrace, Greece',
'Tripoli, Peloponnese, Greece',
'Corinth, Peloponnese, Greece',
'Trikala, Thessaly, Greece',
'Lamia, Central Greece, Greece',
'Katerini, Central Macedonia, Greece',
'Veria, Central Macedonia, Greece',
'Kilkis, Central Macedonia, Greece',
'Kozani, Western Macedonia, Greece',
'Ptolemaida, Western Macedonia, Greece',
'Grevena, Western Macedonia, Greece',
'Florina, Western Macedonia, Greece',
'Edessa, Central Macedonia, Greece',
'Orestiada, Eastern Macedonia and Thrace, Greece',
'Sparta, Peloponnese, Greece',
'Pyrgos, Western Greece, Greece',
'Preveza, Epirus, Greece',
'Agrinio, Western Greece, Greece',
'Messolonghi, Western Greece, Greece',
'Thebes, Central Greece, Greece',
'Livadeia, Central Greece, Greece',
'Karpenisi, Central Greece, Greece',
'Karditsa, Thessaly, Greece',
'Skopelos, Thessaly, Greece',
'Samos, North Aegean, Greece',
'Mytilene, North Aegean, Greece',
'Hydra, Attica, Greece',
'Kifisia, Attica, Greece',
'Marousi, Attica, Greece',
'Piraeus, Attica, Greece',
'Glyfada, Attica, Greece',
'Peristeri, Attica, Greece',
'Kallithea, Attica, Greece',
'Nea Smyrni, Attica, Greece',
'Petroupoli, Attica, Greece',
'Zografou, Attica, Greece',
'Agios Dimitrios, Attica, Greece',
'Agia Paraskevi, Attica, Greece',
'Haidari, Attica, Greece',
'Alimos, Attica, Greece',
'Cholargos, Attica, Greece',
'Dafni, Attica, Greece',
'Elefsina, Attica, Greece',
'Kamatero, Attica, Greece',
'Keratsini, Attica, Greece',
'Nikaia, Attica, Greece',
'Pallini, Attica, Greece',
'Paiania, Attica, Greece',
'Pefki, Attica, Greece',
'Perama, Attica, Greece',
'Tavros, Attica, Greece',
'Voula, Attica, Greece',
'Vouliagmeni, Attica, Greece',
'Kastoria, Western Macedonia, Greece',
'Naousa, Central Macedonia, Greece',
'Ptolemaida, Western Macedonia, Greece',
'Thiva, Central Greece, Greece',
'Chaidari, Attica, Greece',
'Nea Ionia, Attica, Greece',
'Ilion, Attica, Greece',
'Agioi Anargyroi, Attica, Greece',
'Ano Liosia, Attica, Greece',
'Aigaleo, Attica, Greece',
'Amaliada, Western Greece, Greece',
'Argos, Peloponnese, Greece',
'Arta, Epirus, Greece',
'Eleusis, Attica, Greece',
'Ermoupoli, South Aegean, Greece',
'Giannitsa, Central Macedonia, Greece',
'Ierapetra, Crete, Greece',
'Kalamaria, Central Macedonia, Greece',
'Kardamitsia, Epirus, Greece',
'Katerini, Central Macedonia, Greece',
'Kavala, Eastern Macedonia and Thrace, Greece',
'Kifisia, Attica, Greece',
'Komotini, Eastern Macedonia and Thrace, Greece',
'Kozani, Western Macedonia, Greece',
'Kyparissia, Peloponnese, Greece',
'Loutraki, Peloponnese, Greece',
'Markopoulo, Attica, Greece',
'Mykonos, South Aegean, Greece',
'Nafplio, Peloponnese, Greece',
'Nikaia, Attica, Greece',
'Oraiokastro, Central Macedonia, Greece',
'Palaio Faliro, Attica, Greece',
'Pallini, Attica, Greece',
'Pefki, Attica, Greece',
'Polichni, Central Macedonia, Greece',
'Preveza, Epirus, Greece',
'Rafina, Attica, Greece',
'Rethymno, Crete, Greece',
'Salamina, Attica, Greece',
'Sparta, Peloponnese, Greece',
'Thermi, Central Macedonia, Greece',
'Tinos, South Aegean, Greece',
'Trikala, Thessaly, Greece',
'Xanthi, Eastern Macedonia and Thrace, Greece',

// FRANCE
'Paris, Île-de-France, France',
'Lyon, Auvergne-Rhône-Alpes, France',
`Marseille, Provence-Alpes-Côte d'Azur, France`,
'Toulouse, Occitanie, France',
`Nice, Provence-Alpes-Côte d'Azur, France`,
'Nantes, Pays de la Loire, France',
'Strasbourg, Grand Est, France',
'Montpellier, Occitanie, France',
'Bordeaux, Nouvelle-Aquitaine, France',
'Lille, Hauts-de-France, France',
'Reims, Grand Est, France',
'Le Havre, Normandy, France',
'Saint-Étienne, Auvergne-Rhône-Alpes, France',
`Toulon, Provence-Alpes-Côte d'Azur, France`,
'Grenoble, Auvergne-Rhône-Alpes, France',
'Dijon, Bourgogne-Franche-Comté, France',
'Angers, Pays de la Loire, France',
'Villeurbanne, Auvergne-Rhône-Alpes, France',
'Saint-Denis, Île-de-France, France',
'Le Mans, Pays de la Loire, France',
'Clermont-Ferrand, Auvergne-Rhône-Alpes, France',
`Aix-en-Provence, Provence-Alpes-Côte d'Azur, France`,
'Brest, Brittany, France',
'Limoges, Nouvelle-Aquitaine, France',
'Tours, Centre-Val de Loire, France',
'Amiens, Hauts-de-France, France',
'Perpignan, Occitanie, France',
'Metz, Grand Est, France',
'Besançon, Bourgogne-Franche-Comté, France',
'Orléans, Centre-Val de Loire, France',
'Mulhouse, Grand Est, France',
'Rouen, Normandy, France',
'Caen, Normandy, France',
'Nancy, Grand Est, France',
'Saint-Paul, Réunion, France',
'Argenteuil, Île-de-France, France',
'Montreuil, Île-de-France, France',
'Roubaix, Hauts-de-France, France',
'Dunkerque, Hauts-de-France, France',
'Nanterre, Île-de-France, France',
`Avignon, Provence-Alpes-Côte d'Azur, France`,
'Vitry-sur-Seine, Île-de-France, France',
'Créteil, Île-de-France, France',
'Poitiers, Nouvelle-Aquitaine, France',
'Asnières-sur-Seine, Île-de-France, France',
'Courbevoie, Île-de-France, France',
'Versailles, Île-de-France, France',
'Colombes, Île-de-France, France',
'Fort-de-France, Martinique, France',
'Cherbourg-en-Cotentin, Normandy, France',
'Aulnay-sous-Bois, Île-de-France, France',
'Rueil-Malmaison, Île-de-France, France',
'Pau, Nouvelle-Aquitaine, France',
'Béziers, Occitanie, France',
'La Rochelle, Nouvelle-Aquitaine, France',
`Antibes, Provence-Alpes-Côte d'Azur, France`,
'Calais, Hauts-de-France, France',
'Boulogne-Billancourt, Île-de-France, France',
'Argenteuil, Île-de-France, France',
'Montreuil, Île-de-France, France',
'Saint-Denis, Île-de-France, France',
'Aubervilliers, Île-de-France, France',
'Versailles, Île-de-France, France',
'Colombes, Île-de-France, France',
'Courbevoie, Île-de-France, France',
'Nanterre, Île-de-France, France',
'Asnières-sur-Seine, Île-de-France, France',
'Rueil-Malmaison, Île-de-France, France',
'Vitry-sur-Seine, Île-de-France, France',
'Aulnay-sous-Bois, Île-de-France, France',
'Levallois-Perret, Île-de-France, France',
'Ivry-sur-Seine, Île-de-France, France',
'Antony, Île-de-France, France',
'Montreuil, Île-de-France, France',
'Saint-Denis, Île-de-France, France',
'Créteil, Île-de-France, France',
'Boulogne-Billancourt, Île-de-France, France',
'Argenteuil, Île-de-France, France',
'Nanterre, Île-de-France, France',
'Aubervilliers, Île-de-France, France',
'Versailles, Île-de-France, France',
'Colombes, Île-de-France, France',
'Courbevoie, Île-de-France, France',
'Asnières-sur-Seine, Île-de-France, France',
'Rueil-Malmaison, Île-de-France, France',
'Vitry-sur-Seine, Île-de-France, France',
'Aulnay-sous-Bois, Île-de-France, France',
'Levallois-Perret, Île-de-France, France',
'Ivry-sur-Seine, Île-de-France, France',
'Antony, Île-de-France, France',
'Poitiers, Nouvelle-Aquitaine, France',
'Perpignan, Occitanie, France',
'Limoges, Nouvelle-Aquitaine, France',
'Tours, Centre-Val de Loire, France',
'Besançon, Bourgogne-Franche-Comté, France',
'Orléans, Centre-Val de Loire, France',
'Amiens, Hauts-de-France, France',
'Metz, Grand Est, France',
'Mulhouse, Grand Est, France',
'Rouen, Normandy, France',
'Caen, Normandy, France',
'Nancy, Grand Est, France',
'Boulogne-Billancourt, Île-de-France, France',
'Argenteuil, Île-de-France, France',
'Montreuil, Île-de-France, France',
'Saint-Denis, Île-de-France, France',
'Aubervilliers, Île-de-France, France',
'Versailles, Île-de-France, France',
'Colombes, Île-de-France, France',
'Courbevoie, Île-de-France, France',
'Nanterre, Île-de-France, France',
'Asnières-sur-Seine, Île-de-France, France',
'Rueil-Malmaison, Île-de-France, France',
'Vitry-sur-Seine, Île-de-France, France',
'Aulnay-sous-Bois, Île-de-France, France',
'Levallois-Perret, Île-de-France, France',
'Ivry-sur-Seine, Île-de-France, France',
'Antony, Île-de-France, France',

// TURKEY

'Istanbul, Istanbul, Turkey',
'Ankara, Ankara, Turkey',
'Izmir, Izmir, Turkey',
'Bursa, Bursa, Turkey',
'Adana, Adana, Turkey',
'Gaziantep, Gaziantep, Turkey',
'Konya, Konya, Turkey',
'Antalya, Antalya, Turkey',
'Kayseri, Kayseri, Turkey',
'Mersin, Mersin, Turkey',
'Eskişehir, Eskişehir, Turkey',
'Diyarbakır, Diyarbakır, Turkey',
'Samsun, Samsun, Turkey',
'Denizli, Denizli, Turkey',
'Şanlıurfa, Şanlıurfa, Turkey',
'Malatya, Malatya, Turkey',
'Kahramanmaraş, Kahramanmaraş, Turkey',
'Van, Van, Turkey',
'Sakarya, Sakarya, Turkey',
'Erzurum, Erzurum, Turkey',
'Batman, Batman, Turkey',
'Balıkesir, Balıkesir, Turkey',
'Manisa, Manisa, Turkey',
'Elazığ, Elazığ, Turkey',
'Afyonkarahisar, Afyonkarahisar, Turkey',
'Kütahya, Kütahya, Turkey',
'Trabzon, Trabzon, Turkey',
'Zonguldak, Zonguldak, Turkey',
'Adıyaman, Adıyaman, Turkey',
'Muğla, Muğla, Turkey',
'Tekirdağ, Tekirdağ, Turkey',
'Kocaeli, Kocaeli, Turkey',
'Edirne, Edirne, Turkey',
'Çanakkale, Çanakkale, Turkey',
'Giresun, Giresun, Turkey',
'Rize, Rize, Turkey',
'Kars, Kars, Turkey',
'Ordu, Ordu, Turkey',
'Sinop, Sinop, Turkey',
'Nevşehir, Nevşehir, Turkey',
'Niğde, Niğde, Turkey',
'Sivas, Sivas, Turkey',
'Tokat, Tokat, Turkey',
'Yozgat, Yozgat, Turkey',
'Uşak, Uşak, Turkey',
'Karaman, Karaman, Turkey',
'Kırıkkale, Kırıkkale, Turkey',
'Osmaniye, Osmaniye, Turkey',
'Düzce, Düzce, Turkey',
'Karabük, Karabük, Turkey',
'Bolu, Bolu, Turkey',
'Kırklareli, Kırklareli, Turkey',
'Aksaray, Aksaray, Turkey',
'Burdur, Burdur, Turkey',
'Isparta, Isparta, Turkey',
'Artvin, Artvin, Turkey',
'Bartın, Bartın, Turkey',
'Bilecik, Bilecik, Turkey',
'Bitlis, Bitlis, Turkey',
'Hakkari, Hakkari, Turkey',
'Mardin, Mardin, Turkey',
'Siirt, Siirt, Turkey',
'Şırnak, Şırnak, Turkey',
'Van, Van, Turkey',
'Yalova, Yalova, Turkey',
'Çorum, Çorum, Turkey',
'Kastamonu, Kastamonu, Turkey',
'Amasya, Amasya, Turkey',
'Bayburt, Bayburt, Turkey',
'Ardahan, Ardahan, Turkey',
'Iğdır, Iğdır, Turkey',
'Bartın, Bartın, Turkey',
'Karaman, Karaman, Turkey',
'Kırıkkale, Kırıkkale, Turkey',
'Kilis, Kilis, Turkey',
'Sakarya, Sakarya, Turkey',
'Şanlıurfa, Şanlıurfa, Turkey',
'Uşak, Uşak, Turkey',
'Bartın, Bartın, Turkey',
'Gümüşhane, Gümüşhane, Turkey',
'Kırıkkale, Kırıkkale, Turkey',
'Tunceli, Tunceli, Turkey',
'Erzincan, Erzincan, Turkey',
'Gümüşhane, Gümüşhane, Turkey',
'Tunceli, Tunceli, Turkey',
'Kilis, Kilis, Turkey',

// RUSSIA
'Moscow, Moscow, Russia',
'Saint Petersburg, Saint Petersburg, Russia',
'Novosibirsk, Novosibirsk, Russia',
'Yekaterinburg, Sverdlovsk, Russia',
'Nizhny Novgorod, Nizhny Novgorod, Russia',
'Kazan, Tatarstan, Russia',
'Chelyabinsk, Chelyabinsk, Russia',
'Samara, Samara, Russia',
'Omsk, Omsk, Russia',
'Rostov-on-Don, Rostov, Russia',
'Ufa, Bashkortostan, Russia',
'Krasnoyarsk, Krasnoyarsk, Russia',
'Perm, Perm, Russia',
'Voronezh, Voronezh, Russia',
'Volgograd, Volgograd, Russia',
'Krasnodar, Krasnodar, Russia',
'Saratov, Saratov, Russia',
'Tyumen, Tyumen, Russia',
'Tolyatti, Samara, Russia',
'Izhevsk, Udmurtia, Russia',
'Barnaul, Altai Krai, Russia',
'Ulyanovsk, Ulyanovsk, Russia',
'Irkutsk, Irkutsk, Russia',
'Khabarovsk, Khabarovsk, Russia',
'Yaroslavl, Yaroslavl, Russia',
'Vladivostok, Primorsky Krai, Russia',
'Makhachkala, Dagestan, Russia',
'Tomsk, Tomsk, Russia',
'Orenburg, Orenburg, Russia',
'Kemerovo, Kemerovo, Russia',
'Novokuznetsk, Kemerovo, Russia',
'Ryazan, Ryazan, Russia',
'Astrakhan, Astrakhan, Russia',
'Naberezhnye Chelny, Tatarstan, Russia',
'Penza, Penza, Russia',
'Lipi, Lipetsk, Russia',
'Tula, Tula, Russia',
'Kirov, Kirov, Russia',
'Cheboksary, Chuvashia, Russia',
'Kaliningrad, Kaliningrad, Russia',
'Bryansk, Bryansk, Russia',
'Kursk, Kursk, Russia',
'Stavropol, Stavropol, Russia',
'Ulan-Ude, Buryatia, Russia',
'Tver, Tver, Russia',
'Magnitogorsk, Chelyabinsk, Russia',
'Ivanovo, Ivanovo, Russia',
'Sochi, Krasnodar, Russia',
'Belgorod, Belgorod, Russia',
'Surgut, Khanty-Mansi, Russia',
'Vladimir, Vladimir, Russia',
'Chita, Zabaykalsky Krai, Russia',
'Arkhangelsk, Arkhangelsk, Russia',
'Kaluga, Kaluga, Russia',
'Saransk, Mordovia, Russia',
'Smolensk, Smolensk, Russia',
'Vologda, Vologda, Russia',
'Yakutsk, Sakha, Russia',
'Syktyvkar, Komi, Russia',
'Grozny, Chechnya, Russia',
'Kurgan, Kurgan, Russia',
'Vladikavkaz, North Ossetia-Alania, Russia',
'Tambov, Tambov, Russia',
'Petrozavodsk, Karelia, Russia',
'Kostroma, Kostroma, Russia',
'Novorossiysk, Krasnodar, Russia',
'Yoshkar-Ola, Mari El, Russia',
'Taganrog, Rostov, Russia',
'Komsomolsk-on-Amur, Khabarovsk, Russia',
'Sterlitamak, Bashkortostan, Russia',
'Nizhnevartovsk, Khanty-Mansi, Russia',
'Nalchik, Kabardino-Balkaria, Russia',
'Shakhty, Rostov, Russia',
'Biysk, Altai Krai, Russia',
'Veliky Novgorod, Novgorod, Russia',
'Pskov, Pskov, Russia',
'Engels, Saratov, Russia',
'Rybinsk, Yaroslavl, Russia',
'Balakovo, Saratov, Russia',
'Severodvinsk, Arkhangelsk, Russia',
'Armavir, Krasnodar, Russia',
'Podolsk, Moscow, Russia',
'Korolev, Moscow, Russia',
'Mytishchi, Moscow, Russia',
'Khimki, Moscow, Russia',
'Noginsk, Moscow, Russia',
'Zheleznodorozhny, Moscow, Russia',
'Elektrostal, Moscow, Russia',
'Kolomna, Moscow, Russia',
'Odintsovo, Moscow, Russia',
'Balashikha, Moscow, Russia',
'Domodedovo, Moscow, Russia',
'Krasnogorsk, Moscow, Russia',

// ITALY

'Rome, Lazio, Italy',
'Milan, Lombardy, Italy',
'Naples, Campania, Italy',
'Turin, Piedmont, Italy',
'Palermo, Sicily, Italy',
'Genoa, Liguria, Italy',
'Bologna, Emilia-Romagna, Italy',
'Florence, Tuscany, Italy',
'Bari, Apulia, Italy',
'Catania, Sicily, Italy',
'Venice, Veneto, Italy',
'Verona, Veneto, Italy',
'Messina, Sicily, Italy',
'Padua, Veneto, Italy',
'Trieste, Friuli Venezia Giulia, Italy',
'Brescia, Lombardy, Italy',
'Parma, Emilia-Romagna, Italy',
'Taranto, Apulia, Italy',
'Modena, Emilia-Romagna, Italy',
'Reggio Calabria, Calabria, Italy',
'Reggio Emilia, Emilia-Romagna, Italy',
'Perugia, Umbria, Italy',
'Livorno, Tuscany, Italy',
'Ravenna, Emilia-Romagna, Italy',
'Foggia, Apulia, Italy',
'Rimini, Emilia-Romagna, Italy',
'Syracuse, Sicily, Italy',
'Ferrara, Emilia-Romagna, Italy',
'Sassari, Sardinia, Italy',
'Monza, Lombardy, Italy',
'Latina, Lazio, Italy',
'Bergamo, Lombardy, Italy',
'Pescara, Abruzzo, Italy',
'Trento, Trentino-Alto Adige, Italy',
'Forlì, Emilia-Romagna, Italy',
'Vicenza, Veneto, Italy',
'Terni, Umbria, Italy',
'Novara, Piedmont, Italy',
'Piacenza, Emilia-Romagna, Italy',
'Ancona, Marche, Italy',
'Andria, Apulia, Italy',
'Arezzo, Tuscany, Italy',
'Asti, Piedmont, Italy',
'Avellino, Campania, Italy',
'Barletta, Apulia, Italy',
'Belluno, Veneto, Italy',
'Benevento, Campania, Italy',
'Busto Arsizio, Lombardy, Italy',
'Caserta, Campania, Italy',
'Catanzaro, Calabria, Italy',
'Cesena, Emilia-Romagna, Italy',
'Cosenza, Calabria, Italy',
'Cremona, Lombardy, Italy',
'Crotone, Calabria, Italy',
'Fano, Marche, Italy',
'Grosseto, Tuscany, Italy',
'Lecce, Apulia, Italy',
'Lodi, Lombardy, Italy',
'Mantua, Lombardy, Italy',
'Massa, Tuscany, Italy',
'Matera, Basilicata, Italy',
'Molfetta, Apulia, Italy',
'Pavia, Lombardy, Italy',
'Pisa, Tuscany, Italy',
'Potenza, Basilicata, Italy',
'Prato, Tuscany, Italy',
'Ragusa, Sicily, Italy',
'Rieti, Lazio, Italy',
'Savona, Liguria, Italy',
'Teramo, Abruzzo, Italy',
'Treviso, Veneto, Italy',
'Udine, Friuli Venezia Giulia, Italy',
'Varese, Lombardy, Italy',
'Vercelli, Piedmont, Italy',
'Vibo Valentia, Calabria, Italy',
'Viterbo, Lazio, Italy',

//GERMANY

'Berlin, Berlin, Germany',
'Hamburg, Hamburg, Germany',
'Munich, Bavaria, Germany',
'Cologne, North Rhine-Westphalia, Germany',
'Frankfurt, Hesse, Germany',
'Stuttgart, Baden-Württemberg, Germany',
'Düsseldorf, North Rhine-Westphalia, Germany',
'Dortmund, North Rhine-Westphalia, Germany',
'Essen, North Rhine-Westphalia, Germany',
'Leipzig, Saxony, Germany',
'Bremen, Bremen, Germany',
'Dresden, Saxony, Germany',
'Hanover, Lower Saxony, Germany',
'Nuremberg, Bavaria, Germany',
'Duisburg, North Rhine-Westphalia, Germany',
'Bochum, North Rhine-Westphalia, Germany',
'Wuppertal, North Rhine-Westphalia, Germany',
'Bielefeld, North Rhine-Westphalia, Germany',
'Bonn, North Rhine-Westphalia, Germany',
'Münster, North Rhine-Westphalia, Germany',
'Karlsruhe, Baden-Württemberg, Germany',
'Mannheim, Baden-Württemberg, Germany',
'Augsburg, Bavaria, Germany',
'Wiesbaden, Hesse, Germany',
'Gelsenkirchen, North Rhine-Westphalia, Germany',
'Mönchengladbach, North Rhine-Westphalia, Germany',
'Braunschweig, Lower Saxony, Germany',
'Chemnitz, Saxony, Germany',
'Kiel, Schleswig-Holstein, Germany',
'Aachen, North Rhine-Westphalia, Germany',
'Halle, Saxony-Anhalt, Germany',
'Magdeburg, Saxony-Anhalt, Germany',
'Freiburg, Baden-Württemberg, Germany',
'Krefeld, North Rhine-Westphalia, Germany',
'Lübeck, Schleswig-Holstein, Germany',
'Oberhausen, North Rhine-Westphalia, Germany',
'Erfurt, Thuringia, Germany',
'Mainz, Rhineland-Palatinate, Germany',
'Rostock, Mecklenburg-Vorpommern, Germany',
'Kassel, Hesse, Germany',
'Hagen, North Rhine-Westphalia, Germany',
'Hamm, North Rhine-Westphalia, Germany',
'Saarbrücken, Saarland, Germany',
'Mülheim, North Rhine-Westphalia, Germany',
'Potsdam, Brandenburg, Germany',
'Ludwigshafen, Rhineland-Palatinate, Germany',
'Oldenburg, Lower Saxony, Germany',
'Leverkusen, North Rhine-Westphalia, Germany',
'Osnabrück, Lower Saxony, Germany',
'Solingen, North Rhine-Westphalia, Germany',
'Heidelberg, Baden-Württemberg, Germany',
'Herne, North Rhine-Westphalia, Germany',
'Neuss, North Rhine-Westphalia, Germany',
'Darmstadt, Hesse, Germany',
'Paderborn, North Rhine-Westphalia, Germany',
'Regensburg, Bavaria, Germany',
'Ingolstadt, Bavaria, Germany',
'Würzburg, Bavaria, Germany',
'Wolfsburg, Lower Saxony, Germany',
'Ulm, Baden-Württemberg, Germany',
'Heilbronn, Baden-Württemberg, Germany',
'Pforzheim, Baden-Württemberg, Germany',
'Göttingen, Lower Saxony, Germany',
'Bottrop, North Rhine-Westphalia, Germany',
'Reutlingen, Baden-Württemberg, Germany',
'Koblenz, Rhineland-Palatinate, Germany',
'Bremerhaven, Bremen, Germany',
'Erlangen, Bavaria, Germany',
'Trier, Rhineland-Palatinate, Germany',
'Jena, Thuringia, Germany',
'Siegen, North Rhine-Westphalia, Germany',
'Gütersloh, North Rhine-Westphalia, Germany',
'Offenbach, Hesse, Germany',
'Schwerin, Mecklenburg-Vorpommern, Germany',
'Witten, North Rhine-Westphalia, Germany',
'Salzgitter, Lower Saxony, Germany',
'Kaiserslautern, Rhineland-Palatinate, Germany',
'Gera, Thuringia, Germany',
'Iserlohn, North Rhine-Westphalia, Germany',
'Hildesheim, Lower Saxony, Germany',
'Zwickau, Saxony, Germany',
'Ratingen, North Rhine-Westphalia, Germany',
'Marl, North Rhine-Westphalia, Germany',
'Konstanz, Baden-Württemberg, Germany',
'Villingen-Schwenningen, Baden-Württemberg, Germany',
'Lünen, North Rhine-Westphalia, Germany',
'Worms, Rhineland-Palatinate, Germany',
'Velbert, North Rhine-Westphalia, Germany',
'Minden, North Rhine-Westphalia, Germany',
'Dessau-Roßlau, Saxony-Anhalt, Germany',
'Neumünster, Schleswig-Holstein, Germany',
'Delmenhorst, Lower Saxony, Germany',
'Rüsselsheim, Hesse, Germany',
'Bamberg, Bavaria, Germany',
'Flensburg, Schleswig-Holstein, Germany',
'Gladbeck, North Rhine-Westphalia, Germany',
'Konstanz, Baden-Württemberg, Germany',
'Wilhelmshaven, Lower Saxony, Germany',
  ];
  
  export default suggestionsList;
  